### ISSUE TITLE
Exclude local.py from being pushed to AML

### ISSUE THREAD

**Issue by karolzak** [bepuca/azureml-scaffolding#13]
The way I see it, `local.py` is my local playground and since it's never meant to be used in AML job environment it shouldn't be part of the snapshot. At least that would be my expectation.
This can either be handled by simply excluding `local.py` from being copied or we could add a mechanism for users to define something like `exclude_list` so that files put on this list wouldn't make it to AML Job snapshot.
What do you think @bepuca and @Chris-hughes10 ?

![image](https://user-images.githubusercontent.com/9843623/217544659-decb6738-eb18-4686-bbc8-a5d812005d50.png)

**Comment by Chris-hughes10** [comment]
Would adding an `.almignore` file to the experiment solve this?

**Comment by karolzak** [comment]
> Would adding an `.almignore` file to the experiment solve this?

I think it should help. I can add a PR for it sometime next week,
